version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dynalink
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      placement:
        constraints: [node.labels.host==03]
      replicas: 1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints: [node.labels.host==03]
      replicas: 1

volumes:
  mysql_data:

